# THIS NOTEBOOK IS TO TEST THAT THE MODULES WORK AS EXPECTED
# WIP

In [1]:
import ProcessOptimizer
from ProcessOptimizer.space import Integer, Real, Space
from ProcessOptimizer.doe import get_optimal_DOE

In [2]:
print(ProcessOptimizer.__version__)

1.0.0_RUCT


In [ ]:
factor_space = Space(dimensions=[Integer(10, 40, name='ul_indicator'),
                                 Integer(20, 100, name='ul_base'),
                                 Integer(10, 50, name='ul_acid1'),
                                 Integer(10, 50, name='ul_acid2'),
                                 Integer(30, 40, name='temp'),
                                 Real(5.0, 25.0, name='time')
                                ])

design, factor_names = get_optimal_DOE(factor_space, 96, 
                                       design_type='response',
                                       model=None,
                                       replicate=2,
                                       sorting='random')

#design, factor_names = get_optimal_DOE(factor_space, 14, design_type='optimization')

In [16]:
print(design)
print(factor_names)

[[ 40  20  20]
 [ 40  20  20]
 [ 32  20  42]
 [ 32  20  42]
 [ 18  35  78]
 [ 18  35  78]
 [ 32  49 100]
 [ 32  49 100]
 [ 10 100 100]
 [ 10 100 100]
 [ 10  20 100]
 [ 10  20 100]
 [ 10 100  20]
 [ 10 100  20]
 [ 10  49  49]
 [ 10  49  49]
 [ 40 100 100]
 [ 40 100 100]
 [ 10  20  20]
 [ 10  20  20]
 [ 18  78  35]
 [ 18  78  35]
 [ 40 100  20]
 [ 40 100  20]
 [ 40  20 100]
 [ 40  20 100]
 [ 35  78  78]
 [ 35  78  78]]
['ul_indicator', 'ul_base', 'ul_acid']


In [7]:
factor_space = Space(dimensions=[Integer(10, 40, name='ul_indicator'),
                                     Integer(20, 100, name='ul_base'),
                                     Integer(20, 100, name='ul_acid'),
                                     ])

factor_names = factor_space.names

my_model1 = f'{factor_names[0]} + {factor_names[1]} + {factor_names[2]} + {factor_names[0]}:{factor_names[1]} + {factor_names[0]}:{factor_names[2]}'

design, factor_names = get_optimal_DOE(factor_space, 6, model=my_model1, replicates=4, sorting="random_but_group_replicates")

In [8]:
print(design)
print(factor_names)

[[ 40 100  20]
 [ 40 100  20]
 [ 40 100  20]
 [ 40 100  20]
 [ 40  20  20]
 [ 40  20  20]
 [ 40  20  20]
 [ 40  20  20]
 [ 10  20  20]
 [ 10  20  20]
 [ 10  20  20]
 [ 10  20  20]
 [ 10 100  20]
 [ 10 100  20]
 [ 10 100  20]
 [ 10 100  20]
 [ 40 100 100]
 [ 40 100 100]
 [ 40 100 100]
 [ 40 100 100]
 [ 10 100 100]
 [ 10 100 100]
 [ 10 100 100]
 [ 10 100 100]]
['ul_indicator', 'ul_base', 'ul_acid']


In [15]:
import numpy as np
a= np.tile(design, (1, 2))
a2 = np.reshape(a, (12, 3))
print(a)
print(a2)

[[ 10 100 100  10 100 100]
 [ 10 100  20  10 100  20]
 [ 40  20  20  40  20  20]
 [ 40 100 100  40 100 100]
 [ 40  20 100  40  20 100]
 [ 10  20 100  10  20 100]]
[[ 10 100 100]
 [ 10 100 100]
 [ 10 100  20]
 [ 10 100  20]
 [ 40  20  20]
 [ 40  20  20]
 [ 40 100 100]
 [ 40 100 100]
 [ 40  20 100]
 [ 40  20 100]
 [ 10  20 100]
 [ 10  20 100]]


In [6]:
factor_names = factor_space.names
my_model1 = f'{factor_names[0]} + {factor_names[1]} + {factor_names[2]} + {factor_names[0]}:{factor_names[1]} + {factor_names[0]}:{factor_names[2]} + {factor_names[1]}:{factor_names[2]}'
print(my_model1)

ul_indicator + ul_base + ul_acid + ul_indicator:ul_base + ul_indicator:ul_acid + ul_base:ul_acid


In [8]:
get_optimal_DOE(factor_space, 7, model=my_model1)

([[10.0, 100, 20],
  [10.0, 100, 100],
  [40.0, 20, 100],
  [40.0, 100, 100],
  [10.0, 20, 100],
  [40.0, 100, 20],
  [10.0, 20, 20]],
 ['ul_indicator', 'ul_base', 'ul_acid'])

In [12]:
my_model2 = f'{factor_names[0]} + {factor_names[1]} + {factor_names[2]} + pow({factor_names[1]}, 2)'
print(my_model2)

ul_indicator + ul_base + ul_acid + pow(ul_base, 2)


In [13]:
get_optimal_DOE(factor_space, 7, model=my_model2)

([[10.0, 64, 100],
  [40.0, 100, 100],
  [40.0, 20, 20],
  [40.0, 64, 20],
  [40.0, 56, 100],
  [10.0, 20, 100],
  [10.0, 100, 20]],
 ['ul_indicator', 'ul_base', 'ul_acid'])